<?php

namespace App\Http\Controllers\Subordinate;

use PDF;
use Auth;
use Carbon\Carbon;
use App\Models\School;
use App\Models\Payment;
use Illuminate\Support\Str;
use App\Models\PaymentRecord;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class PdfController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:subordinate');
        $this->middleware('subordinate-banned');
        $this->middleware('checktwofa');
    }

    public function letterHead(School $school)
    {
        $code = Str::random(6);
        $upperCode = strtoupper($code);
        $title = "This document belongs to ".$school->name.".";
        $date = date("d-m-Y",strtotime(now()));
        $generatedBy = Auth::user()->salutation." ".Auth::user()->first_name." ".Auth::user()->last_name;
        $downloadTitle = $title." "."Generated by: ".$generatedBy." on ".$date.". Ref: ".$upperCode;
        $pdf = PDF::loadView('subordinate.pdf.letter_head',['school'=>$school,'title'=>$title,'downloadTitle'=>$downloadTitle])->setOptions(['dpi'=>150,'defaultFont'=>'sans-serif','isRemoteEnabled' => true,'isHtml5ParserEnabled' => true])->setPaper('a4','potrait');
        $pdf->output();
        $canvas = $pdf->getDomPDF()->getCanvas();
        $height = $canvas->get_height();
        $width = $canvas->get_width();
        $imageUrl = public_path('/storage/storage/'.$school->image);
        $imageWidth = 250;
        $imageHeight = 250;
        $y = (($height-$imageHeight)/2);
        $x = (($width-$imageWidth)/2);
        $canvas->set_opacity(.2,"Multiply");
        $canvas->image($imageUrl,$x,$y,$imageWidth,$imageHeight,$resolution='normal');
        $canvas->page_text($width/5, $height/2,strtoupper('Original Copy'),null,70, array(0,0,0),2,2,-30);
        
        return $pdf->download($downloadTitle.'.pdf');
    }

    public function instantDownload(School $school,Request $request)
    {
        $code = Str::random(6);
        $content = $request->content;
        $title = $school->name." "."document. Generated By".Auth::user()->full_name." "."On".now().". Code:".$code;
        $downloadTitle = $title;
        $pdf = PDF::loadView('subordinate.pdf.instant_download',['school'=>$school,'title'=>$title,'content'=>$content,'downloadTitle'=>$downloadTitle])->setOptions(['dpi'=>150,'defaultFont'=>'sans-serif','isRemoteEnabled' => true,'isHtml5ParserEnabled' => true])->setPaper('a4','potrait');
        $pdf->output();
        $canvas = $pdf->getDomPDF()->getCanvas();
        $height = $canvas->get_height();
        $width = $canvas->get_width();
        $canvas->set_opacity(.2,"Multiply");
        $canvas->page_text($width/5, $height/2,strtoupper('Original Copy'),null,70, array(0,0,0),2,2,-30);
        
        return $pdf->download($downloadTitle.'.pdf');
    }
}
