<?php

namespace App\Http\Controllers\Staff;

use PDF;
use Auth;
use Carbon\Carbon;
use App\Models\School;
use App\Models\Payment;
use Illuminate\Support\Str;
use App\Models\PaymentRecord;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class PdfController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:staff');
        $this->middleware('banned');
        $this->middleware('staff2fa');
    }

    public function letterHead(School $school)
    {
        $code = Str::random(6);
        $title = $school->name." "."Letter Head. Generated By".Auth::user()->full_name." "."On".now().". Code:".$code;
        $downloadTitle = $school->name." ".'Letter Head';
        $pdf = PDF::loadView('staff.pdf.letter_head',['school'=>$school,'title'=>$title])->setOptions(['dpi'=>150,'defaultFont'=>'sans-serif','isRemoteEnabled' => true,'isHtml5ParserEnabled' => true])->setPaper('a4','potrait');
        $pdf->output();
        $canvas = $pdf->getDomPDF()->getCanvas();
        $height = $canvas->get_height();
        $width = $canvas->get_width();
        $imageUrl = public_path('/storage/storage/'.$school->image);
        $imageWidth = 250;
        $imageHeight = 250;
        $y = (($height-$imageHeight)/2);
        $x = (($width-$imageWidth)/2);
        $canvas->set_opacity(.2,"Multiply");
        $canvas->image($imageUrl,$x,$y,$imageWidth,$imageHeight,$resolution='normal');
        $canvas->page_text($width/5, $height/2,strtoupper('Original Copy'),null,70, array(0,0,0),2,2,-30);
        
        return $pdf->download($downloadTitle.'.pdf');
    }

    public function instantDownload(School $school,Request $request)
    {
        $code = Str::random(6);
        $content = $request->content;
        $title = $school->name." "."document. Generated By".Auth::user()->full_name." "."On".now().". Code:".$code;
        $pdf = PDF::loadView('staff.pdf.instant_download',['school'=>$school,'title'=>$title,'content'=>$content])->setOptions(['dpi'=>150,'defaultFont'=>'sans-serif','isRemoteEnabled' => true,'isHtml5ParserEnabled' => true])->setPaper('a4','potrait');
        $pdf->output();
        $canvas = $pdf->getDomPDF()->getCanvas();
        $height = $canvas->get_height();
        $width = $canvas->get_width();
        $canvas->set_opacity(.2,"Multiply");
        $canvas->page_text($width/5, $height/2,strtoupper('Original Copy'),null,70, array(0,0,0),2,2,-30);
        
        return $pdf->download($title.'.pdf');
    }
}
