<?php

namespace App\Http\Controllers\Admin\Pdf;

use Auth;
use PDF;
use Illuminate\Support\Str;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class SchoolLetterheadPdfController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:admin');
        $this->middleware('admin-banned');
        $this->middleware('checktwofa');
    }

    public function schoolLetterHead()
    {
        $school = Auth::user()->school;
        $code = Str::random(6);
        $upperCode = strtoupper($code);
        $title = "This document belongs to ".$school->name.".";
        $date = date("d-m-Y",strtotime(now()));
        $generatedBy = Auth::user()->salutation." ".Auth::user()->first_name." ".Auth::user()->last_name;
        $downloadTitle = $title." "."Generated by: ".$generatedBy." on ".$date.". Ref: ".$upperCode;
        $pdf = PDF::loadView('admin.pdf.letter_head',['school'=>$school,'title'=>$title,'downloadTitle'=>$downloadTitle])->setOptions(['dpi'=>150,'defaultFont'=>'sans-serif','isRemoteEnabled' => true,'isHtml5ParserEnabled' => true])->setPaper('a4','potrait');
        $pdf->output();
        $canvas = $pdf->getDomPDF()->getCanvas();
        $height = $canvas->get_height();
        $width = $canvas->get_width();
        $imageUrl = public_path('/storage/storage/'.$school->image);
        $imageWidth = 250;
        $imageHeight = 250;
        $y = (($height-$imageHeight)/2);
        $x = (($width-$imageWidth)/2);
        $canvas->set_opacity(.2,"Multiply");
        $canvas->image($imageUrl,$x,$y,$imageWidth,$imageHeight,$resolution='normal');
        $canvas->page_text($width/5, $height/2,strtoupper('Original Copy'),null,70, array(0,0,0),2,2,-30);
        
        return $pdf->download($downloadTitle.'.pdf');
    }
}
